{
    "file": "/home/azmain/snr_fixed/hibernate_class_1.java",
    "java_code": "package hibernate;\n//ID = 520902\n\nimport library.dao.UserDAO;\nimport org.hibernate.Session;\nimport org.hibernate.SessionFactory;\nimport org.hibernate.cfg.AnnotationConfiguration;\nimport library.model.User;\nimport org.hibernate.Transaction;\n\npublic class hibernate_class_1 {\n\tpublic class HibernateUserDAO implements UserDAO {\n\n\t\tprivate SessionFactory sessionFactory;\n\n\t\tpublic HibernateUserDAO() {\n\t\t\tAnnotationConfiguration annotConf = new AnnotationConfiguration();\n\t\t\tannotConf.addAnnotatedClass(User.class);\n\t\t\tannotConf.configure();\n\t\t\t// The line below generates the exception!\n\t\t\tsessionFactory = annotConf.buildSessionFactory();\n\t\t}\n\n\t\tpublic void store(User user) {\n\t\t\tSession session = sessionFactory.openSession();\n\t\t\tTransaction tx = session.getTransaction();\n\t\t\ttry {\n\t\t\t\ttx.begin();\n\t\t\t\tsession.saveOrUpdate(user);\n\t\t\t\ttx.commit();\n\t\t\t} catch (RuntimeException e) {\n\t\t\t\ttx.rollback();\n\t\t\t\tthrow e;\n\t\t\t} finally {\n\t\t\t\tsession.close();\n\t\t\t}\n\t\t}\n\n\t\t@Override\n\t\tpublic User getUser(int arg0) {\n\t\t\t// TODO Auto-generated method stub\n\t\t\treturn null;\n\t\t}\n\n\t\t@Override\n\t\tpublic User getUserByFirstLastName(String arg0, String arg1) {\n\t\t\t// TODO Auto-generated method stub\n\t\t\treturn null;\n\t\t}\n\n\t\t@Override\n\t\tpublic User getUserByUsername(String arg0) {\n\t\t\t// TODO Auto-generated method stub\n\t\t\treturn null;\n\t\t}\n\n\t\t@Override\n\t\tpublic int saveUser(User arg0) {\n\t\t\t// TODO Auto-generated method stub\n\t\t\treturn 0;\n\t\t}\n\t}\n}",
    "stdout": "",
    "stderr": "",
    "return_code": 0
}